import { __ } from "@wordpress/i18n";
import { Dashicon } from "@wordpress/components";

// the consts defined here should be unique from one another
export const WRAPPER_BG = "wrprBg";
export const WRAPPER_MARGIN = "wrpMargin";
export const WRAPPER_PADDING = "wrpPadding";
export const WRAPPER_BORDER_SHADOW = "wrpBorderShadow";
export const TITLE_MARGIN = "titleMargin";
export const SUBTITLE_MARGIN = "subtitleMargin";
export const separator_MARGIN = "separatorMargin";
export const separator_LINE_SIZE = "separatorLineSize";
export const separator_ICON_SIZE = "separatorIconSize";
export const separator_WIDTH = "separatorWidth";

export const UNIT_TYPES = [
	{ label: "px", value: "px" },
	{ label: "em", value: "em" },
];

export const separator_UNIT_TYPES = [
	{ label: "px", value: "px" },
	{ label: "%", value: "%" },
	{ label: "em", value: "em" },
];

export const NORMAL_HOVER = [
	{ label: "Normal", value: "normal" },
	{ label: "Hover", value: "hover" },
];

export const separator_TYPE = [
	{ label: __("Line", "smart-heading"), value: "line" },
	{ label: __("Icon", "smart-heading"), value: "icon" },
];

export const separator_POSITION = [
	{ label: __("Top", "smart-heading"), value: "top" },
	{ label: __("Bottom", "smart-heading"), value: "bottom" },
];

export const subheading_POSITION = [
	{ label: __("Top", "smart-heading"), value: "top" },
	{ label: __("Bottom", "smart-heading"), value: "bottom" },
];

export const PRESETS = [
	{ label: __("Default", "smart-heading"), value: "preset-0" },
	{ label: __("Preset 1", "smart-heading"), value: "preset-1" },
	{ label: __("Preset 2", "smart-heading"), value: "preset-2" },
	{ label: __("Preset 3", "smart-heading"), value: "preset-3" },
];

export const TEXT_ALIGN = [
	{ label: __(<Dashicon icon={"editor-alignleft"} />), value: "left" },
	{ label: __(<Dashicon icon={"editor-aligncenter"} />), value: "center" },
	{ label: __(<Dashicon icon={"editor-alignright"} />), value: "right" },
	{ label: __(<Dashicon icon={"menu"} />), value: "justify" }
];

export const HEADING = [
	{ label: __("H1", "smart-heading"), value: "h1" },
	{ label: __("H2", "smart-heading"), value: "h2" },
	{ label: __("H3", "smart-heading"), value: "h3" },
	{ label: __("H4", "smart-heading"), value: "h4" },
	{ label: __("H5", "smart-heading"), value: "h5" },
	{ label: __("H6", "smart-heading"), value: "h6" },
	{ label: __("P", "smart-heading"), value: "p" },
	{ label: __("Div", "smart-heading"), value: "div" },
];

export const SEPERATOR_STYLES = [
	{ label: __("Solid", "smart-heading"), value: "solid" },
	{ label: __("Dashed", "smart-heading"), value: "dashed" },
	{ label: __("Dotted", "smart-heading"), value: "dotted" },
	{ label: __("Double", "smart-heading"), value: "double" },
	{ label: __("Groove", "smart-heading"), value: "groove" },
	{ label: __("Outset", "smart-heading"), value: "outset" },
	{ label: __("Ridge", "smart-heading"), value: "ridge" },
];

export const FONT_FAMILYS = [
    { label: __("Default", "smart-heading"), value: "Default" },
    { label: __("ABeeZee", "smart-heading"), value: "ABeeZee" },
    { label: __("Abel", "smart-heading"), value: "Abel" },
    { label: __("Abhaya Libre", "smart-heading"), value: "Abhaya Libre" },
    { label: __("Abril Fatface", "smart-heading"), value: "Abril Fatface" },
    { label: __("Abyssinica SIL", "smart-heading"), value: "Abyssinica SIL" },
    { label: __("Aclonica", "smart-heading"), value: "Aclonica" },
    { label: __("Acme", "smart-heading"), value: "Acme" },
    { label: __("Actor", "smart-heading"), value: "Actor" },
    { label: __("Adamina", "smart-heading"), value: "Adamina" },
    { label: __("Adobe Blank", "smart-heading"), value: "Adobe Blank" },
    { label: __("Advent Pro", "smart-heading"), value: "Advent Pro" },
    { label: __("Aguafina Script", "smart-heading"), value: "Aguafina Script" },
    { label: __("Akronim", "smart-heading"), value: "Akronim" },
    { label: __("aksarabaligalang", "smart-heading"), value: "aksarabaligalang" },
    { label: __("Aladin", "smart-heading"), value: "Aladin" },
    { label: __("Aldrich", "smart-heading"), value: "Aldrich" },
    { label: __("Alef", "smart-heading"), value: "Alef" },
    { label: __("alefhebrew", "smart-heading"), value: "alefhebrew" },
    { label: __("Alegreya", "smart-heading"), value: "Alegreya" },
    { label: __("Alegreya Sans", "smart-heading"), value: "Alegreya Sans" },
    { label: __("Alegreya Sans SC", "smart-heading"), value: "Alegreya Sans SC" },
    { label: __("Alegreya SC", "smart-heading"), value: "Alegreya SC" },
    { label: __("Aleo", "smart-heading"), value: "Aleo" },
    { label: __("Alex Brush", "smart-heading"), value: "Alex Brush" },
    { label: __("Alfa Slab One", "smart-heading"), value: "Alfa Slab One" },
    { label: __("Alice", "smart-heading"), value: "Alice" },
    { label: __("Alike", "smart-heading"), value: "Alike" },
    { label: __("Alike Angular", "smart-heading"), value: "Alike Angular" },
    { label: __("Allan", "smart-heading"), value: "Allan" },
    { label: __("Allerta", "smart-heading"), value: "Allerta" },
    { label: __("Allerta Stencil", "smart-heading"), value: "Allerta Stencil" },
    { label: __("Allura", "smart-heading"), value: "Allura" },
    { label: __("Almendra", "smart-heading"), value: "Almendra" },
    { label: __("Almendra Display", "smart-heading"), value: "Almendra Display" },
    { label: __("Almendra SC", "smart-heading"), value: "Almendra SC" },
    { label: __("Amarante", "smart-heading"), value: "Amarante" },
    { label: __("Amaranth", "smart-heading"), value: "Amaranth" },
    { label: __("Amatic SC", "smart-heading"), value: "Amatic SC" },
    { label: __("Amethysta", "smart-heading"), value: "Amethysta" },
    { label: __("Amiko", "smart-heading"), value: "Amiko" },
    { label: __("Amiri", "smart-heading"), value: "Amiri" },
    { label: __("Amita", "smart-heading"), value: "Amita" },
    { label: __("amstelvaralpha", "smart-heading"), value: "amstelvaralpha" },
    { label: __("Anaheim", "smart-heading"), value: "Anaheim" },
    { label: __("Andada", "smart-heading"), value: "Andada" },
    { label: __("Andada SC", "smart-heading"), value: "Andada SC" },
    { label: __("Andika", "smart-heading"), value: "Andika" },
    { label: __("Angkor", "smart-heading"), value: "Angkor" },
    { label: __("Annie Use Your Telescope", "smart-heading"), value: "Annie Use Your Telescope" },
    { label: __("Anonymous Pro", "smart-heading"), value: "Anonymous Pro" },
    { label: __("Antic", "smart-heading"), value: "Antic" },
    { label: __("Antic Didone", "smart-heading"), value: "Antic Didone" },
    { label: __("Antic Slab", "smart-heading"), value: "Antic Slab" },
    { label: __("Anton", "smart-heading"), value: "Anton" },
    { label: __("Antonio", "smart-heading"), value: "Antonio" },
    { label: __("Arapey", "smart-heading"), value: "Arapey" },
    { label: __("Arbutus", "smart-heading"), value: "Arbutus" },
    { label: __("Arbutus Slab", "smart-heading"), value: "Arbutus Slab" },
    { label: __("Architects Daughter", "smart-heading"), value: "Architects Daughter" },
    { label: __("Archivo", "smart-heading"), value: "Archivo" },
    { label: __("Archivo Black", "smart-heading"), value: "Archivo Black" },
    { label: __("Archivo Narrow", "smart-heading"), value: "Archivo Narrow" },
    { label: __("archivovfbeta", "smart-heading"), value: "archivovfbeta" },
    { label: __("Aref Ruqaa", "smart-heading"), value: "Aref Ruqaa" },
    { label: __("Arima Madurai", "smart-heading"), value: "Arima Madurai" },
    { label: __("Arimo", "smart-heading"), value: "Arimo" },
    { label: __("Arizonia", "smart-heading"), value: "Arizonia" },
    { label: __("Armata", "smart-heading"), value: "Armata" },
    { label: __("Arsenal", "smart-heading"), value: "Arsenal" },
    { label: __("Artifika", "smart-heading"), value: "Artifika" },
    { label: __("Arvo", "smart-heading"), value: "Arvo" },
    { label: __("Arya", "smart-heading"), value: "Arya" },
    { label: __("Asap", "smart-heading"), value: "Asap" },
    { label: __("Asap Condensed", "smart-heading"), value: "Asap Condensed" },
    { label: __("asapvfbeta", "smart-heading"), value: "asapvfbeta" },
    { label: __("Asar", "smart-heading"), value: "Asar" },
    { label: __("Asset", "smart-heading"), value: "Asset" },
    { label: __("Assistant", "smart-heading"), value: "Assistant" },
    { label: __("Astloch", "smart-heading"), value: "Astloch" },
    { label: __("Asul", "smart-heading"), value: "Asul" },
    { label: __("Athiti", "smart-heading"), value: "Athiti" },
    { label: __("Atomic Age", "smart-heading"), value: "Atomic Age" },
    { label: __("Aubrey", "smart-heading"), value: "Aubrey" },
    { label: __("Audiowide", "smart-heading"), value: "Audiowide" },
    { label: __("Autour One", "smart-heading"), value: "Autour One" },
    { label: __("Average", "smart-heading"), value: "Average" },
    { label: __("Average Sans", "smart-heading"), value: "Average Sans" },
    { label: __("Averia Gruesa Libre", "smart-heading"), value: "Averia Gruesa Libre" },
    { label: __("Averia Libre", "smart-heading"), value: "Averia Libre" },
    { label: __("Averia Sans Libre", "smart-heading"), value: "Averia Sans Libre" },
    { label: __("Averia Serif Libre", "smart-heading"), value: "Averia Serif Libre" },
    { label: __("B612", "smart-heading"), value: "B612" },
    { label: __("B612 Mono", "smart-heading"), value: "B612 Mono" },
    { label: __("Bad Script", "smart-heading"), value: "Bad Script" },
    { label: __("Bahiana", "smart-heading"), value: "Bahiana" },
    { label: __("Bahianita", "smart-heading"), value: "Bahianita" },
    { label: __("Bai Jamjuree", "smart-heading"), value: "Bai Jamjuree" },
    { label: __("Baloo", "smart-heading"), value: "Baloo" },
    { label: __("Baloo Bhai", "smart-heading"), value: "Baloo Bhai" },
    { label: __("Baloo Bhaijaan", "smart-heading"), value: "Baloo Bhaijaan" },
    { label: __("Baloo Bhaina", "smart-heading"), value: "Baloo Bhaina" },
    { label: __("Baloo Chettan", "smart-heading"), value: "Baloo Chettan" },
    { label: __("Baloo Da", "smart-heading"), value: "Baloo Da" },
    { label: __("Baloo Paaji", "smart-heading"), value: "Baloo Paaji" },
    { label: __("Baloo Tamma", "smart-heading"), value: "Baloo Tamma" },
    { label: __("Baloo Tammudu", "smart-heading"), value: "Baloo Tammudu" },
    { label: __("Baloo Thambi", "smart-heading"), value: "Baloo Thambi" },
    { label: __("Balthazar", "smart-heading"), value: "Balthazar" },
    { label: __("Bangers", "smart-heading"), value: "Bangers" },
    { label: __("Barlow", "smart-heading"), value: "Barlow" },
    { label: __("Barlow Condensed", "smart-heading"), value: "Barlow Condensed" },
    { label: __("Barlow Semi Condensed", "smart-heading"), value: "Barlow Semi Condensed" },
    { label: __("Barriecito", "smart-heading"), value: "Barriecito" },
    { label: __("Barrio", "smart-heading"), value: "Barrio" },
    { label: __("Basic", "smart-heading"), value: "Basic" },
    { label: __("Battambang", "smart-heading"), value: "Battambang" },
    { label: __("Baumans", "smart-heading"), value: "Baumans" },
    { label: __("Bayon", "smart-heading"), value: "Bayon" },
    { label: __("Belgrano", "smart-heading"), value: "Belgrano" },
    { label: __("Bellefair", "smart-heading"), value: "Bellefair" },
    { label: __("Belleza", "smart-heading"), value: "Belleza" },
    { label: __("BenchNine", "smart-heading"), value: "BenchNine" },
    { label: __("Bentham", "smart-heading"), value: "Bentham" },
    { label: __("Berkshire Swash", "smart-heading"), value: "Berkshire Swash" },
    { label: __("Beth Ellen", "smart-heading"), value: "Beth Ellen" },
    { label: __("Bevan", "smart-heading"), value: "Bevan" },
    { label: __("Bhavuka", "smart-heading"), value: "Bhavuka" },
    { label: __("Bigelow Rules", "smart-heading"), value: "Bigelow Rules" },
    { label: __("Bigshot One", "smart-heading"), value: "Bigshot One" },
    { label: __("Bilbo", "smart-heading"), value: "Bilbo" },
    { label: __("Bilbo Swash Caps", "smart-heading"), value: "Bilbo Swash Caps" },
    { label: __("Bio Rhyme", "smart-heading"), value: "Bio Rhyme" },
    { label: __("Bio Rhyme Expanded", "smart-heading"), value: "Bio Rhyme Expanded" },
    { label: __("Biryani", "smart-heading"), value: "Biryani" },
    { label: __("Bitter", "smart-heading"), value: "Bitter" },
    { label: __("Black And White Picture", "smart-heading"), value: "Black And White Picture" },
    { label: __("Black Han Sans", "smart-heading"), value: "Black Han Sans" },
    { label: __("Black Ops One", "smart-heading"), value: "Black Ops One" },
    { label: __("Bokor", "smart-heading"), value: "Bokor" },
    { label: __("Bonbon", "smart-heading"), value: "Bonbon" },
    { label: __("Boogaloo", "smart-heading"), value: "Boogaloo" },
    { label: __("Bowlby One", "smart-heading"), value: "Bowlby One" },
    { label: __("Bowlby One SC", "smart-heading"), value: "Bowlby One SC" },
    { label: __("Brawler", "smart-heading"), value: "Brawler" },
    { label: __("Bree Serif", "smart-heading"), value: "Bree Serif" },
    { label: __("Bruno Ace", "smart-heading"), value: "Bruno Ace" },
    { label: __("Bruno Ace SC", "smart-heading"), value: "Bruno Ace SC" },
    { label: __("Bubblegum Sans", "smart-heading"), value: "Bubblegum Sans" },
    { label: __("Bubbler One", "smart-heading"), value: "Bubbler One" },
    { label: __("Buda", "smart-heading"), value: "Buda" },
    { label: __("Buenard", "smart-heading"), value: "Buenard" },
    { label: __("Bungee", "smart-heading"), value: "Bungee" },
    { label: __("Bungee Hairline", "smart-heading"), value: "Bungee Hairline" },
    { label: __("Bungee Inline", "smart-heading"), value: "Bungee Inline" },
    { label: __("Bungee Outline", "smart-heading"), value: "Bungee Outline" },
    { label: __("Bungee Shade", "smart-heading"), value: "Bungee Shade" },
    { label: __("Butcherman", "smart-heading"), value: "Butcherman" },
    { label: __("Butcherman Caps", "smart-heading"), value: "Butcherman Caps" },
    { label: __("Butterfly Kids", "smart-heading"), value: "Butterfly Kids" },
    { label: __("Cabin", "smart-heading"), value: "Cabin" },
    { label: __("Cabin Condensed", "smart-heading"), value: "Cabin Condensed" },
    { label: __("Cabin Sketch", "smart-heading"), value: "Cabin Sketch" },
    { label: __("cabinvfbeta", "smart-heading"), value: "cabinvfbeta" },
    { label: __("Caesar Dressing", "smart-heading"), value: "Caesar Dressing" },
    { label: __("Cagliostro", "smart-heading"), value: "Cagliostro" },
    { label: __("Cairo", "smart-heading"), value: "Cairo" },
    { label: __("Calligraffitti", "smart-heading"), value: "Calligraffitti" },
    { label: __("Cambay", "smart-heading"), value: "Cambay" },
    { label: __("Cambo", "smart-heading"), value: "Cambo" },
    { label: __("Candal", "smart-heading"), value: "Candal" },
    { label: __("Cantarell", "smart-heading"), value: "Cantarell" },
    { label: __("Cantata One", "smart-heading"), value: "Cantata One" },
    { label: __("Cantora One", "smart-heading"), value: "Cantora One" },
    { label: __("Capriola", "smart-heading"), value: "Capriola" },
    { label: __("Cardo", "smart-heading"), value: "Cardo" },
    { label: __("Carme", "smart-heading"), value: "Carme" },
    { label: __("Carrois Gothic", "smart-heading"), value: "Carrois Gothic" },
    { label: __("Carrois Gothic SC", "smart-heading"), value: "Carrois Gothic SC" },
    { label: __("Carter One", "smart-heading"), value: "Carter One" },
    { label: __("Catamaran", "smart-heading"), value: "Catamaran" },
    { label: __("Caudex", "smart-heading"), value: "Caudex" },
    { label: __("Caveat", "smart-heading"), value: "Caveat" },
    { label: __("Caveat Brush", "smart-heading"), value: "Caveat Brush" },
    { label: __("Cedarville Cursive", "smart-heading"), value: "Cedarville Cursive" },
    { label: __("Ceviche One", "smart-heading"), value: "Ceviche One" },
    { label: __("Chakra Petch", "smart-heading"), value: "Chakra Petch" },
    { label: __("Changa", "smart-heading"), value: "Changa" },
    { label: __("Changa One", "smart-heading"), value: "Changa One" },
    { label: __("Chango", "smart-heading"), value: "Chango" },
    { label: __("Charm", "smart-heading"), value: "Charm" },
    { label: __("Charmonman", "smart-heading"), value: "Charmonman" },
    { label: __("Chau Philomene One", "smart-heading"), value: "Chau Philomene One" },
    { label: __("Chela One", "smart-heading"), value: "Chela One" },
    { label: __("Chelsea Market", "smart-heading"), value: "Chelsea Market" },
    { label: __("Chenla", "smart-heading"), value: "Chenla" },
    { label: __("Cherry Cream Soda", "smart-heading"), value: "Cherry Cream Soda" },
    { label: __("Cherry Swash", "smart-heading"), value: "Cherry Swash" },
    { label: __("Chewy", "smart-heading"), value: "Chewy" },
    { label: __("Chicle", "smart-heading"), value: "Chicle" },
    { label: __("Chilanka", "smart-heading"), value: "Chilanka" },
    { label: __("Chivo", "smart-heading"), value: "Chivo" },
    { label: __("Chonburi", "smart-heading"), value: "Chonburi" },
    { label: __("Cinzel", "smart-heading"), value: "Cinzel" },
    { label: __("Cinzel Decorative", "smart-heading"), value: "Cinzel Decorative" },
    { label: __("Clicker Script", "smart-heading"), value: "Clicker Script" },
    { label: __("Coda", "smart-heading"), value: "Coda" },
    { label: __("Coda Caption", "smart-heading"), value: "Coda Caption" },
    { label: __("Codystar", "smart-heading"), value: "Codystar" },
    { label: __("Coiny", "smart-heading"), value: "Coiny" },
    { label: __("Combo", "smart-heading"), value: "Combo" },
    { label: __("Comfortaa", "smart-heading"), value: "Comfortaa" },
    { label: __("Coming Soon", "smart-heading"), value: "Coming Soon" },
    { label: __("Concert One", "smart-heading"), value: "Concert One" },
    { label: __("Condiment", "smart-heading"), value: "Condiment" },
    { label: __("Content", "smart-heading"), value: "Content" },
    { label: __("Contrail One", "smart-heading"), value: "Contrail One" },
    { label: __("Convergence", "smart-heading"), value: "Convergence" },
    { label: __("Cookie", "smart-heading"), value: "Cookie" },
    { label: __("Copse", "smart-heading"), value: "Copse" },
    { label: __("Corben", "smart-heading"), value: "Corben" },
    { label: __("Cormorant", "smart-heading"), value: "Cormorant" },
    { label: __("Cormorant Garamond", "smart-heading"), value: "Cormorant Garamond" },
    { label: __("Cormorant Infant", "smart-heading"), value: "Cormorant Infant" },
    { label: __("Cormorant SC", "smart-heading"), value: "Cormorant SC" },
    { label: __("Cormorant Unicase", "smart-heading"), value: "Cormorant Unicase" },
    { label: __("Cormorant Upright", "smart-heading"), value: "Cormorant Upright" },
    { label: __("Courgette", "smart-heading"), value: "Courgette" },
    { label: __("Cousine", "smart-heading"), value: "Cousine" },
    { label: __("Coustard", "smart-heading"), value: "Coustard" },
    { label: __("Covered By Your Grace", "smart-heading"), value: "Covered By Your Grace" },
    { label: __("Crafty Girls", "smart-heading"), value: "Crafty Girls" },
    { label: __("Creepster", "smart-heading"), value: "Creepster" },
    { label: __("Creepster Caps", "smart-heading"), value: "Creepster Caps" },
    { label: __("Crete Round", "smart-heading"), value: "Crete Round" },
    { label: __("Crimson Pro", "smart-heading"), value: "Crimson Pro" },
    { label: __("Crimson Text", "smart-heading"), value: "Crimson Text" },
    { label: __("Croissant One", "smart-heading"), value: "Croissant One" },
    { label: __("Crushed", "smart-heading"), value: "Crushed" },
    { label: __("Cuprum", "smart-heading"), value: "Cuprum" },
    { label: __("Cute Font", "smart-heading"), value: "Cute Font" },
    { label: __("Cutive", "smart-heading"), value: "Cutive" },
    { label: __("Cutive Mono", "smart-heading"), value: "Cutive Mono" },
    { label: __("Damion", "smart-heading"), value: "Damion" },
    { label: __("Dancing Script", "smart-heading"), value: "Dancing Script" },
    { label: __("Dangrek", "smart-heading"), value: "Dangrek" },
    { label: __("Darker Grotesque", "smart-heading"), value: "Darker Grotesque" },
    { label: __("Dawning of a New Day", "smart-heading"), value: "Dawning of a New Day" },
    { label: __("Days One", "smart-heading"), value: "Days One" },
    { label: __("decovaralpha", "smart-heading"), value: "decovaralpha" },
    { label: __("Dekko", "smart-heading"), value: "Dekko" },
    { label: __("Delius", "smart-heading"), value: "Delius" },
    { label: __("Delius Swash Caps", "smart-heading"), value: "Delius Swash Caps" },
    { label: __("Delius Unicase", "smart-heading"), value: "Delius Unicase" },
    { label: __("Della Respira", "smart-heading"), value: "Della Respira" },
    { label: __("Denk One", "smart-heading"), value: "Denk One" },
    { label: __("Devonshire", "smart-heading"), value: "Devonshire" },
    { label: __("Dhurjati", "smart-heading"), value: "Dhurjati" },
    { label: __("Dhyana", "smart-heading"), value: "Dhyana" },
    { label: __("Didact Gothic", "smart-heading"), value: "Didact Gothic" },
    { label: __("Digital Numbers", "smart-heading"), value: "Digital Numbers" },
    { label: __("Diplomata", "smart-heading"), value: "Diplomata" },
    { label: __("Diplomata SC", "smart-heading"), value: "Diplomata SC" },
    { label: __("DM Sans", "smart-heading"), value: "DM Sans" },
    { label: __("DM Serif Display", "smart-heading"), value: "DM Serif Display" },
    { label: __("DM Serif Text", "smart-heading"), value: "DM Serif Text" },
    { label: __("Do Hyeon", "smart-heading"), value: "Do Hyeon" },
    { label: __("Dokdo", "smart-heading"), value: "Dokdo" },
    { label: __("Domine", "smart-heading"), value: "Domine" },
    { label: __("Donegal One", "smart-heading"), value: "Donegal One" },
    { label: __("Doppio One", "smart-heading"), value: "Doppio One" },
    { label: __("Dorsa", "smart-heading"), value: "Dorsa" },
    { label: __("Dosis", "smart-heading"), value: "Dosis" },
    { label: __("Dr Sugiyama", "smart-heading"), value: "Dr Sugiyama" },
    { label: __("Duru Sans", "smart-heading"), value: "Duru Sans" },
    { label: __("Dynalight", "smart-heading"), value: "Dynalight" },
    { label: __("Eagle Lake", "smart-heading"), value: "Eagle Lake" },
    { label: __("East Sea Dokdo", "smart-heading"), value: "East Sea Dokdo" },
    { label: __("Eater", "smart-heading"), value: "Eater" },
    { label: __("Eater Caps", "smart-heading"), value: "Eater Caps" },
    { label: __("EB Garamond", "smart-heading"), value: "EB Garamond" },
    { label: __("Economica", "smart-heading"), value: "Economica" },
    { label: __("Eczar", "smart-heading"), value: "Eczar" },
    { label: __("Ek Mukta", "smart-heading"), value: "Ek Mukta" },
    { label: __("El Messiri", "smart-heading"), value: "El Messiri" },
    { label: __("Electrolize", "smart-heading"), value: "Electrolize" },
    { label: __("Elsie", "smart-heading"), value: "Elsie" },
    { label: __("Elsie Swash Caps", "smart-heading"), value: "Elsie Swash Caps" },
    { label: __("Emblema One", "smart-heading"), value: "Emblema One" },
    { label: __("Emilys Candy", "smart-heading"), value: "Emilys Candy" },
    { label: __("Encode Sans", "smart-heading"), value: "Encode Sans" },
    { label: __("Encode Sans Condensed", "smart-heading"), value: "Encode Sans Condensed" },
    { label: __("Encode Sans Expanded", "smart-heading"), value: "Encode Sans Expanded" },
    { label: __("Encode Sans Semi Condensed", "smart-heading"), value: "Encode Sans Semi Condensed" },
    { label: __("Encode Sans Semi Expanded", "smart-heading"), value: "Encode Sans Semi Expanded" },
    { label: __("Engagement", "smart-heading"), value: "Engagement" },
    { label: __("Englebert", "smart-heading"), value: "Englebert" },
    { label: __("Enriqueta", "smart-heading"), value: "Enriqueta" },
    { label: __("Erica One", "smart-heading"), value: "Erica One" },
    { label: __("Esteban", "smart-heading"), value: "Esteban" },
    { label: __("Euphoria Script", "smart-heading"), value: "Euphoria Script" },
    { label: __("Ewert", "smart-heading"), value: "Ewert" },
    { label: __("Exo", "smart-heading"), value: "Exo" },
    { label: __("Exo 2", "smart-heading"), value: "Exo 2" },
    { label: __("Expletus Sans", "smart-heading"), value: "Expletus Sans" },
    { label: __("Fahkwang", "smart-heading"), value: "Fahkwang" },
    { label: __("Fanwood Text", "smart-heading"), value: "Fanwood Text" },
    { label: __("Farro", "smart-heading"), value: "Farro" },
    { label: __("Farsan", "smart-heading"), value: "Farsan" },
    { label: __("Fascinate", "smart-heading"), value: "Fascinate" },
    { label: __("Fascinate Inline", "smart-heading"), value: "Fascinate Inline" },
    { label: __("Faster One", "smart-heading"), value: "Faster One" },
    { label: __("Fasthand", "smart-heading"), value: "Fasthand" },
    { label: __("Fauna One", "smart-heading"), value: "Fauna One" },
    { label: __("Faustina", "smart-heading"), value: "Faustina" },
    { label: __("faustinavfbeta", "smart-heading"), value: "faustinavfbeta" },
    { label: __("Federant", "smart-heading"), value: "Federant" },
    { label: __("Federo", "smart-heading"), value: "Federo" },
    { label: __("Felipa", "smart-heading"), value: "Felipa" },
    { label: __("Fenix", "smart-heading"), value: "Fenix" },
    { label: __("Finger Paint", "smart-heading"), value: "Finger Paint" },
    { label: __("Fira Code", "smart-heading"), value: "Fira Code" },
    { label: __("Fira Mono", "smart-heading"), value: "Fira Mono" },
    { label: __("Fira Sans", "smart-heading"), value: "Fira Sans" },
    { label: __("Fira Sans Condensed", "smart-heading"), value: "Fira Sans Condensed" },
    { label: __("Fira Sans Extra Condensed", "smart-heading"), value: "Fira Sans Extra Condensed" },
    { label: __("Fjalla One", "smart-heading"), value: "Fjalla One" },
    { label: __("Fjord One", "smart-heading"), value: "Fjord One" },
    { label: __("Flamenco", "smart-heading"), value: "Flamenco" },
    { label: __("Flavors", "smart-heading"), value: "Flavors" },
    { label: __("Fondamento", "smart-heading"), value: "Fondamento" },
    { label: __("Fontdiner Swanky", "smart-heading"), value: "Fontdiner Swanky" },
    { label: __("Forum", "smart-heading"), value: "Forum" },
    { label: __("Francois One", "smart-heading"), value: "Francois One" },
    { label: __("Frank Ruhl Libre", "smart-heading"), value: "Frank Ruhl Libre" },
    { label: __("Freckle Face", "smart-heading"), value: "Freckle Face" },
    { label: __("Fredericka the Great", "smart-heading"), value: "Fredericka the Great" },
    { label: __("Fredoka One", "smart-heading"), value: "Fredoka One" },
    { label: __("Freehand", "smart-heading"), value: "Freehand" },
    { label: __("Fresca", "smart-heading"), value: "Fresca" },
    { label: __("Frijole", "smart-heading"), value: "Frijole" },
    { label: __("Fruktur", "smart-heading"), value: "Fruktur" },
    { label: __("Fugaz One", "smart-heading"), value: "Fugaz One" },
    { label: __("Gabriela", "smart-heading"), value: "Gabriela" },
    { label: __("Gaegu", "smart-heading"), value: "Gaegu" },
    { label: __("Gafata", "smart-heading"), value: "Gafata" },
    { label: __("Galada", "smart-heading"), value: "Galada" },
    { label: __("Galdeano", "smart-heading"), value: "Galdeano" },
    { label: __("Galindo", "smart-heading"), value: "Galindo" },
    { label: __("Gamja Flower", "smart-heading"), value: "Gamja Flower" },
    { label: __("Gayathri", "smart-heading"), value: "Gayathri" },
    { label: __("Gemunu Libre", "smart-heading"), value: "Gemunu Libre" },
    { label: __("Gentium Basic", "smart-heading"), value: "Gentium Basic" },
    { label: __("Gentium Book Basic", "smart-heading"), value: "Gentium Book Basic" },
    { label: __("Geo", "smart-heading"), value: "Geo" },
    { label: __("Geostar", "smart-heading"), value: "Geostar" },
    { label: __("Geostar Fill", "smart-heading"), value: "Geostar Fill" },
    { label: __("Germania One", "smart-heading"), value: "Germania One" },
    { label: __("GFS Didot", "smart-heading"), value: "GFS Didot" },
    { label: __("GFS Neohellenic", "smart-heading"), value: "GFS Neohellenic" },
    { label: __("Gidugu", "smart-heading"), value: "Gidugu" },
    { label: __("Gilda Display", "smart-heading"), value: "Gilda Display" },
    { label: __("Give You Glory", "smart-heading"), value: "Give You Glory" },
    { label: __("Glass Antiqua", "smart-heading"), value: "Glass Antiqua" },
    { label: __("Glegoo", "smart-heading"), value: "Glegoo" },
    { label: __("Gloria Hallelujah", "smart-heading"), value: "Gloria Hallelujah" },
    { label: __("Goblin One", "smart-heading"), value: "Goblin One" },
    { label: __("Gochi Hand", "smart-heading"), value: "Gochi Hand" },
    { label: __("Gorditas", "smart-heading"), value: "Gorditas" },
    { label: __("Gothic A1", "smart-heading"), value: "Gothic A1" },
    { label: __("Goudy Bookletter 1911", "smart-heading"), value: "Goudy Bookletter 1911" },
    { label: __("Graduate", "smart-heading"), value: "Graduate" },
    { label: __("Grand Hotel", "smart-heading"), value: "Grand Hotel" },
    { label: __("Gravitas One", "smart-heading"), value: "Gravitas One" },
    { label: __("Great Vibes", "smart-heading"), value: "Great Vibes" },
    { label: __("Grenze", "smart-heading"), value: "Grenze" },
    { label: __("Griffy", "smart-heading"), value: "Griffy" },
    { label: __("Gruppo", "smart-heading"), value: "Gruppo" },
    { label: __("Gudea", "smart-heading"), value: "Gudea" },
    { label: __("Gugi", "smart-heading"), value: "Gugi" },
    { label: __("Gurajada", "smart-heading"), value: "Gurajada" },
    { label: __("Habibi", "smart-heading"), value: "Habibi" },
    { label: __("Halant", "smart-heading"), value: "Halant" },
    { label: __("Hammersmith One", "smart-heading"), value: "Hammersmith One" },
    { label: __("Hanalei", "smart-heading"), value: "Hanalei" },
    { label: __("Hanalei Fill", "smart-heading"), value: "Hanalei Fill" },
    { label: __("Handlee", "smart-heading"), value: "Handlee" },
    { label: __("hanna", "smart-heading"), value: "hanna" },
    { label: __("hannari", "smart-heading"), value: "hannari" },
    { label: __("Hanuman", "smart-heading"), value: "Hanuman" },
    { label: __("Happy Monkey", "smart-heading"), value: "Happy Monkey" },
    { label: __("Harmattan", "smart-heading"), value: "Harmattan" },
    { label: __("Headland One", "smart-heading"), value: "Headland One" },
    { label: __("Heebo", "smart-heading"), value: "Heebo" },
    { label: __("Henny Penny", "smart-heading"), value: "Henny Penny" },
    { label: __("Hermeneus One", "smart-heading"), value: "Hermeneus One" },
    { label: __("Herr Von Muellerhoff", "smart-heading"), value: "Herr Von Muellerhoff" },
    { label: __("Hi Melody", "smart-heading"), value: "Hi Melody" },
    { label: __("Hind", "smart-heading"), value: "Hind" },
    { label: __("Hind Colombo", "smart-heading"), value: "Hind Colombo" },
    { label: __("Hind Guntur", "smart-heading"), value: "Hind Guntur" },
    { label: __("Hind Jalandhar", "smart-heading"), value: "Hind Jalandhar" },
    { label: __("Hind Kochi", "smart-heading"), value: "Hind Kochi" },
    { label: __("Hind Madurai", "smart-heading"), value: "Hind Madurai" },
    { label: __("Hind Mysuru", "smart-heading"), value: "Hind Mysuru" },
    { label: __("Hind Siliguri", "smart-heading"), value: "Hind Siliguri" },
    { label: __("Hind Vadodara", "smart-heading"), value: "Hind Vadodara" },
    { label: __("Holtwood One SC", "smart-heading"), value: "Holtwood One SC" },
    { label: __("Homemade Apple", "smart-heading"), value: "Homemade Apple" },
    { label: __("Homenaje", "smart-heading"), value: "Homenaje" },
    { label: __("IBM Plex Mono", "smart-heading"), value: "IBM Plex Mono" },
    { label: __("IBM Plex Sans", "smart-heading"), value: "IBM Plex Sans" },
    { label: __("IBM Plex Sans Condensed", "smart-heading"), value: "IBM Plex Sans Condensed" },
    { label: __("IBM Plex Serif", "smart-heading"), value: "IBM Plex Serif" },
    { label: __("Iceberg", "smart-heading"), value: "Iceberg" },
    { label: __("Iceland", "smart-heading"), value: "Iceland" },
    { label: __("IM Fell Double Pica", "smart-heading"), value: "IM Fell Double Pica" },
    { label: __("IM Fell Double Pica SC", "smart-heading"), value: "IM Fell Double Pica SC" },
    { label: __("IM Fell DW Pica", "smart-heading"), value: "IM Fell DW Pica" },
    { label: __("IM Fell DW Pica SC", "smart-heading"), value: "IM Fell DW Pica SC" },
    { label: __("IM Fell English", "smart-heading"), value: "IM Fell English" },
    { label: __("IM Fell English SC", "smart-heading"), value: "IM Fell English SC" },
    { label: __("IM Fell French Canon", "smart-heading"), value: "IM Fell French Canon" },
    { label: __("IM Fell French Canon SC", "smart-heading"), value: "IM Fell French Canon SC" },
    { label: __("IM Fell Great Primer", "smart-heading"), value: "IM Fell Great Primer" },
    { label: __("IM Fell Great Primer SC", "smart-heading"), value: "IM Fell Great Primer SC" },
    { label: __("Imprima", "smart-heading"), value: "Imprima" },
    { label: __("Inconsolata", "smart-heading"), value: "Inconsolata" },
    { label: __("Inder", "smart-heading"), value: "Inder" },
    { label: __("Indie Flower", "smart-heading"), value: "Indie Flower" },
    { label: __("Inika", "smart-heading"), value: "Inika" },
    { label: __("Inknut Antiqua", "smart-heading"), value: "Inknut Antiqua" },
    { label: __("Irish Grover", "smart-heading"), value: "Irish Grover" },
    { label: __("Istok Web", "smart-heading"), value: "Istok Web" },
    { label: __("Italiana", "smart-heading"), value: "Italiana" },
    { label: __("Italianno", "smart-heading"), value: "Italianno" },
    { label: __("Itim", "smart-heading"), value: "Itim" },
    { label: __("Jacques Francois", "smart-heading"), value: "Jacques Francois" },
    { label: __("Jacques Francois Shadow", "smart-heading"), value: "Jacques Francois Shadow" },
    { label: __("Jaldi", "smart-heading"), value: "Jaldi" },
    { label: __("jejugothic", "smart-heading"), value: "jejugothic" },
    { label: __("jejuhallasan", "smart-heading"), value: "jejuhallasan" },
    { label: __("jejumyeongjo", "smart-heading"), value: "jejumyeongjo" },
    { label: __("Jim Nightshade", "smart-heading"), value: "Jim Nightshade" },
    { label: __("Jockey One", "smart-heading"), value: "Jockey One" },
    { label: __("Jolly Lodger", "smart-heading"), value: "Jolly Lodger" },
    { label: __("Jomhuria", "smart-heading"), value: "Jomhuria" },
    { label: __("jomolhari", "smart-heading"), value: "jomolhari" },
    { label: __("Josefin Sans", "smart-heading"), value: "Josefin Sans" },
    { label: __("Josefin Sans Std Light", "smart-heading"), value: "Josefin Sans Std Light" },
    { label: __("Josefin Slab", "smart-heading"), value: "Josefin Slab" },
    { label: __("Joti One", "smart-heading"), value: "Joti One" },
    { label: __("Jua", "smart-heading"), value: "Jua" },
    { label: __("Judson", "smart-heading"), value: "Judson" },
    { label: __("Julee", "smart-heading"), value: "Julee" },
    { label: __("Julius Sans One", "smart-heading"), value: "Julius Sans One" },
    { label: __("Junge", "smart-heading"), value: "Junge" },
    { label: __("Jura", "smart-heading"), value: "Jura" },
    { label: __("Just Another Hand", "smart-heading"), value: "Just Another Hand" },
    { label: __("Just Me Again Down Here", "smart-heading"), value: "Just Me Again Down Here" },
    { label: __("K2D", "smart-heading"), value: "K2D" },
    { label: __("Kadwa", "smart-heading"), value: "Kadwa" },
    { label: __("Kalam", "smart-heading"), value: "Kalam" },
    { label: __("Kameron", "smart-heading"), value: "Kameron" },
    { label: __("Kanit", "smart-heading"), value: "Kanit" },
    { label: __("Kantumruy", "smart-heading"), value: "Kantumruy" },
    { label: __("Karla", "smart-heading"), value: "Karla" },
    { label: __("Karla Tamil Inclined", "smart-heading"), value: "Karla Tamil Inclined" },
    { label: __("Karla Tamil Upright", "smart-heading"), value: "Karla Tamil Upright" },
    { label: __("Karma", "smart-heading"), value: "Karma" },
    { label: __("Katibeh", "smart-heading"), value: "Katibeh" },
    { label: __("Kaushan Script", "smart-heading"), value: "Kaushan Script" },
    { label: __("Kavivanar", "smart-heading"), value: "Kavivanar" },
    { label: __("Kavoon", "smart-heading"), value: "Kavoon" },
    { label: __("Kdam Thmor", "smart-heading"), value: "Kdam Thmor" },
    { label: __("Keania One", "smart-heading"), value: "Keania One" },
    { label: __("Kelly Slab", "smart-heading"), value: "Kelly Slab" },
    { label: __("Kenia", "smart-heading"), value: "Kenia" },
    { label: __("Khand", "smart-heading"), value: "Khand" },
    { label: __("Khmer", "smart-heading"), value: "Khmer" },
    { label: __("Khula", "smart-heading"), value: "Khula" },
    { label: __("khyay", "smart-heading"), value: "khyay" },
    { label: __("Kirang Haerang", "smart-heading"), value: "Kirang Haerang" },
    { label: __("Kite One", "smart-heading"), value: "Kite One" },
    { label: __("Knewave", "smart-heading"), value: "Knewave" },
    { label: __("Kodchasan", "smart-heading"), value: "Kodchasan" },
    { label: __("KoHo", "smart-heading"), value: "KoHo" },
    { label: __("kokoro", "smart-heading"), value: "kokoro" },
    { label: __("kopubbatang", "smart-heading"), value: "kopubbatang" },
    { label: __("Kotta One", "smart-heading"), value: "Kotta One" },
    { label: __("Koulen", "smart-heading"), value: "Koulen" },
    { label: __("Kranky", "smart-heading"), value: "Kranky" },
    { label: __("Kreon", "smart-heading"), value: "Kreon" },
    { label: __("Kristi", "smart-heading"), value: "Kristi" },
    { label: __("Krona One", "smart-heading"), value: "Krona One" },
    { label: __("Krub", "smart-heading"), value: "Krub" },
    { label: __("Kumar One", "smart-heading"), value: "Kumar One" },
    { label: __("Kurale", "smart-heading"), value: "Kurale" },
    { label: __("La Belle Aurore", "smart-heading"), value: "La Belle Aurore" },
    { label: __("Lacquer", "smart-heading"), value: "Lacquer" },
    { label: __("Laila", "smart-heading"), value: "Laila" },
    { label: __("Lakki Reddy", "smart-heading"), value: "Lakki Reddy" },
    { label: __("Lalezar", "smart-heading"), value: "Lalezar" },
    { label: __("Lancelot", "smart-heading"), value: "Lancelot" },
    { label: __("laomuangdon", "smart-heading"), value: "laomuangdon" },
    { label: __("laomuangkhong", "smart-heading"), value: "laomuangkhong" },
    { label: __("laosanspro", "smart-heading"), value: "laosanspro" },
    { label: __("Lateef", "smart-heading"), value: "Lateef" },
    { label: __("Lato", "smart-heading"), value: "Lato" },
    { label: __("League Script", "smart-heading"), value: "League Script" },
    { label: __("Leckerli One", "smart-heading"), value: "Leckerli One" },
    { label: __("Ledger", "smart-heading"), value: "Ledger" },
    { label: __("Lekton", "smart-heading"), value: "Lekton" },
    { label: __("Lemon", "smart-heading"), value: "Lemon" },
    { label: __("Lemonada", "smart-heading"), value: "Lemonada" },
    { label: __("Libre Barcode 128", "smart-heading"), value: "Libre Barcode 128" },
    { label: __("Libre Barcode 128 Text", "smart-heading"), value: "Libre Barcode 128 Text" },
    { label: __("Libre Barcode 39", "smart-heading"), value: "Libre Barcode 39" },
    { label: __("Libre Barcode 39 Extended", "smart-heading"), value: "Libre Barcode 39 Extended" },
    { label: __("Libre Barcode 39 Extended Text", "smart-heading"), value: "Libre Barcode 39 Extended Text" },
    { label: __("Libre Barcode 39 Text", "smart-heading"), value: "Libre Barcode 39 Text" },
    { label: __("Libre Baskerville", "smart-heading"), value: "Libre Baskerville" },
    { label: __("Libre Caslon Display", "smart-heading"), value: "Libre Caslon Display" },
    { label: __("Libre Caslon Text", "smart-heading"), value: "Libre Caslon Text" },
    { label: __("Libre Franklin", "smart-heading"), value: "Libre Franklin" },
    { label: __("Life Savers", "smart-heading"), value: "Life Savers" },
    { label: __("Lilita One", "smart-heading"), value: "Lilita One" },
    { label: __("Lily Script One", "smart-heading"), value: "Lily Script One" },
    { label: __("Limelight", "smart-heading"), value: "Limelight" },
    { label: __("Linden Hill", "smart-heading"), value: "Linden Hill" },
    { label: __("Literata", "smart-heading"), value: "Literata" },
    { label: __("Liu Jian Mao Cao", "smart-heading"), value: "Liu Jian Mao Cao" },
    { label: __("Livvic", "smart-heading"), value: "Livvic" },
    { label: __("Lobster", "smart-heading"), value: "Lobster" },
    { label: __("Lobster Two", "smart-heading"), value: "Lobster Two" },
    { label: __("Lohit Bengali", "smart-heading"), value: "Lohit Bengali" },
    { label: __("Lohit Tamil", "smart-heading"), value: "Lohit Tamil" },
    { label: __("lohitdevanagari", "smart-heading"), value: "lohitdevanagari" },
    { label: __("Londrina Outline", "smart-heading"), value: "Londrina Outline" },
    { label: __("Londrina Shadow", "smart-heading"), value: "Londrina Shadow" },
    { label: __("Londrina Sketch", "smart-heading"), value: "Londrina Sketch" },
    { label: __("Londrina Solid", "smart-heading"), value: "Londrina Solid" },
    { label: __("Long Cang", "smart-heading"), value: "Long Cang" },
    { label: __("Lora", "smart-heading"), value: "Lora" },
    { label: __("Love Ya Like A Sister", "smart-heading"), value: "Love Ya Like A Sister" },
    { label: __("Loved by the King", "smart-heading"), value: "Loved by the King" },
    { label: __("Lovers Quarrel", "smart-heading"), value: "Lovers Quarrel" },
    { label: __("Luckiest Guy", "smart-heading"), value: "Luckiest Guy" },
    { label: __("Lusitana", "smart-heading"), value: "Lusitana" },
    { label: __("Lustria", "smart-heading"), value: "Lustria" },
    { label: __("Ma Shan Zheng", "smart-heading"), value: "Ma Shan Zheng" },
    { label: __("Macondo", "smart-heading"), value: "Macondo" },
    { label: __("Macondo Swash Caps", "smart-heading"), value: "Macondo Swash Caps" },
    { label: __("Mada", "smart-heading"), value: "Mada" },
    { label: __("Magra", "smart-heading"), value: "Magra" },
    { label: __("Maiden Orange", "smart-heading"), value: "Maiden Orange" },
    { label: __("Maitree", "smart-heading"), value: "Maitree" },
    { label: __("Major Mono Display", "smart-heading"), value: "Major Mono Display" },
    { label: __("Mako", "smart-heading"), value: "Mako" },
    { label: __("Mali", "smart-heading"), value: "Mali" },
    { label: __("Mallanna", "smart-heading"), value: "Mallanna" },
    { label: __("Mandali", "smart-heading"), value: "Mandali" },
    { label: __("Manjari", "smart-heading"), value: "Manjari" },
    { label: __("Manuale", "smart-heading"), value: "Manuale" },
    { label: __("Marcellus", "smart-heading"), value: "Marcellus" },
    { label: __("Marcellus SC", "smart-heading"), value: "Marcellus SC" },
    { label: __("Marck Script", "smart-heading"), value: "Marck Script" },
    { label: __("Margarine", "smart-heading"), value: "Margarine" },
    { label: __("Marko One", "smart-heading"), value: "Marko One" },
    { label: __("Marmelad", "smart-heading"), value: "Marmelad" },
    { label: __("Martel", "smart-heading"), value: "Martel" },
    { label: __("Martel Sans", "smart-heading"), value: "Martel Sans" },
    { label: __("Marvel", "smart-heading"), value: "Marvel" },
    { label: __("Mate", "smart-heading"), value: "Mate" },
    { label: __("Mate SC", "smart-heading"), value: "Mate SC" },
    { label: __("Maven Pro", "smart-heading"), value: "Maven Pro" },
    { label: __("mavenprovfbeta", "smart-heading"), value: "mavenprovfbeta" },
    { label: __("McLaren", "smart-heading"), value: "McLaren" },
    { label: __("Meddon", "smart-heading"), value: "Meddon" },
    { label: __("MedievalSharp", "smart-heading"), value: "MedievalSharp" },
    { label: __("Medula One", "smart-heading"), value: "Medula One" },
    { label: __("Meera Inimai", "smart-heading"), value: "Meera Inimai" },
    { label: __("Megrim", "smart-heading"), value: "Megrim" },
    { label: __("Meie Script", "smart-heading"), value: "Meie Script" },
    { label: __("Merge One", "smart-heading"), value: "Merge One" },
    { label: __("Merienda", "smart-heading"), value: "Merienda" },
    { label: __("Merienda One", "smart-heading"), value: "Merienda One" },
    { label: __("Merriweather", "smart-heading"), value: "Merriweather" },
    { label: __("Merriweather Sans", "smart-heading"), value: "Merriweather Sans" },
    { label: __("Mervale Script", "smart-heading"), value: "Mervale Script" },
    { label: __("Metal", "smart-heading"), value: "Metal" },
    { label: __("Metal Mania", "smart-heading"), value: "Metal Mania" },
    { label: __("Metamorphous", "smart-heading"), value: "Metamorphous" },
    { label: __("Metrophobic", "smart-heading"), value: "Metrophobic" },
    { label: __("Miama", "smart-heading"), value: "Miama" },
    { label: __("Michroma", "smart-heading"), value: "Michroma" },
    { label: __("Milonga", "smart-heading"), value: "Milonga" },
    { label: __("Miltonian", "smart-heading"), value: "Miltonian" },
    { label: __("Miltonian Tattoo", "smart-heading"), value: "Miltonian Tattoo" },
    { label: __("Mina", "smart-heading"), value: "Mina" },
    { label: __("Miniver", "smart-heading"), value: "Miniver" },
    { label: __("Miriam Libre", "smart-heading"), value: "Miriam Libre" },
    { label: __("Miss Fajardose", "smart-heading"), value: "Miss Fajardose" },
    { label: __("Miss Saint Delafield", "smart-heading"), value: "Miss Saint Delafield" },
    { label: __("Modak", "smart-heading"), value: "Modak" },
    { label: __("Modern Antiqua", "smart-heading"), value: "Modern Antiqua" },
    { label: __("Molengo", "smart-heading"), value: "Molengo" },
    { label: __("Molle", "smart-heading"), value: "Molle" },
    { label: __("Monda", "smart-heading"), value: "Monda" },
    { label: __("Monofett", "smart-heading"), value: "Monofett" },
    { label: __("Monoton", "smart-heading"), value: "Monoton" },
    { label: __("Monsieur La Doulaise", "smart-heading"), value: "Monsieur La Doulaise" },
    { label: __("Montaga", "smart-heading"), value: "Montaga" },
    { label: __("Montez", "smart-heading"), value: "Montez" },
    { label: __("Montserrat", "smart-heading"), value: "Montserrat" },
    { label: __("Montserrat Alternates", "smart-heading"), value: "Montserrat Alternates" },
    { label: __("Montserrat Subrayada", "smart-heading"), value: "Montserrat Subrayada" },
    { label: __("Moul", "smart-heading"), value: "Moul" },
    { label: __("Moulpali", "smart-heading"), value: "Moulpali" },
    { label: __("Mountains of Christmas", "smart-heading"), value: "Mountains of Christmas" },
    { label: __("Mouse Memoirs", "smart-heading"), value: "Mouse Memoirs" },
    { label: __("mplus1p", "smart-heading"), value: "mplus1p" },
    { label: __("Mr Bedford", "smart-heading"), value: "Mr Bedford" },
    { label: __("Mr Bedfort", "smart-heading"), value: "Mr Bedfort" },
    { label: __("Mr Dafoe", "smart-heading"), value: "Mr Dafoe" },
    { label: __("Mr De Haviland", "smart-heading"), value: "Mr De Haviland" },
    { label: __("Mrs Saint Delafield", "smart-heading"), value: "Mrs Saint Delafield" },
    { label: __("Mrs Sheppards", "smart-heading"), value: "Mrs Sheppards" },
    { label: __("Mukta", "smart-heading"), value: "Mukta" },
    { label: __("Mukta Mahee", "smart-heading"), value: "Mukta Mahee" },
    { label: __("Mukta Malar", "smart-heading"), value: "Mukta Malar" },
    { label: __("Mukta Vaani", "smart-heading"), value: "Mukta Vaani" },
    { label: __("Muli", "smart-heading"), value: "Muli" },
    { label: __("myanmarsanspro", "smart-heading"), value: "myanmarsanspro" },
    { label: __("Mystery Quest", "smart-heading"), value: "Mystery Quest" },
    { label: __("Nanum Brush Script", "smart-heading"), value: "Nanum Brush Script" },
    { label: __("Nanum Gothic", "smart-heading"), value: "Nanum Gothic" },
    { label: __("Nanum Gothic Coding", "smart-heading"), value: "Nanum Gothic Coding" },
    { label: __("Nanum Myeongjo", "smart-heading"), value: "Nanum Myeongjo" },
    { label: __("Nanum Pen Script", "smart-heading"), value: "Nanum Pen Script" },
    { label: __("NATS", "smart-heading"), value: "NATS" },
    { label: __("Neucha", "smart-heading"), value: "Neucha" },
    { label: __("Neuton", "smart-heading"), value: "Neuton" },
    { label: __("New Rocker", "smart-heading"), value: "New Rocker" },
    { label: __("News Cycle", "smart-heading"), value: "News Cycle" },
    { label: __("nicomoji", "smart-heading"), value: "nicomoji" },
    { label: __("Niconne", "smart-heading"), value: "Niconne" },
    { label: __("nikukyu", "smart-heading"), value: "nikukyu" },
    { label: __("Niramit", "smart-heading"), value: "Niramit" },
    { label: __("Nixie One", "smart-heading"), value: "Nixie One" },
    { label: __("Nobile", "smart-heading"), value: "Nobile" },
    { label: __("Nokora", "smart-heading"), value: "Nokora" },
    { label: __("Norican", "smart-heading"), value: "Norican" },
    { label: __("Nosifer", "smart-heading"), value: "Nosifer" },
    { label: __("Nosifer Caps", "smart-heading"), value: "Nosifer Caps" },
    { label: __("Notable", "smart-heading"), value: "Notable" },
    { label: __("Nothing You Could Do", "smart-heading"), value: "Nothing You Could Do" },
    { label: __("Noticia Text", "smart-heading"), value: "Noticia Text" },
    { label: __("Noto Sans", "smart-heading"), value: "Noto Sans" },
    { label: __("Noto Serif", "smart-heading"), value: "Noto Serif" },
    { label: __("notosanstamil", "smart-heading"), value: "notosanstamil" },
    { label: __("Nova Cut", "smart-heading"), value: "Nova Cut" },
    { label: __("Nova Flat", "smart-heading"), value: "Nova Flat" },
    { label: __("Nova Mono", "smart-heading"), value: "Nova Mono" },
    { label: __("Nova Oval", "smart-heading"), value: "Nova Oval" },
    { label: __("Nova Round", "smart-heading"), value: "Nova Round" },
    { label: __("Nova Script", "smart-heading"), value: "Nova Script" },
    { label: __("Nova Slim", "smart-heading"), value: "Nova Slim" },
    { label: __("Nova Square", "smart-heading"), value: "Nova Square" },
    { label: __("NTR", "smart-heading"), value: "NTR" },
    { label: __("Numans", "smart-heading"), value: "Numans" },
    { label: __("Nunito", "smart-heading"), value: "Nunito" },
    { label: __("Nunito Sans", "smart-heading"), value: "Nunito Sans" },
    { label: __("Odor Mean Chey", "smart-heading"), value: "Odor Mean Chey" },
    { label: __("Offside", "smart-heading"), value: "Offside" },
    { label: __("OFL Sorts Mill Goudy TT", "smart-heading"), value: "OFL Sorts Mill Goudy TT" },
    { label: __("Old Standard TT", "smart-heading"), value: "Old Standard TT" },
    { label: __("Oldenburg", "smart-heading"), value: "Oldenburg" },
    { label: __("Oleo Script", "smart-heading"), value: "Oleo Script" },
    { label: __("Oleo Script Swash Caps", "smart-heading"), value: "Oleo Script Swash Caps" },
    { label: __("Open Sans", "smart-heading"), value: "Open Sans" },
    { label: __("Open Sans Condensed", "smart-heading"), value: "Open Sans Condensed" },
    { label: __("opensanshebrew", "smart-heading"), value: "opensanshebrew" },
    { label: __("opensanshebrewcondensed", "smart-heading"), value: "opensanshebrewcondensed" },
    { label: __("Oranienbaum", "smart-heading"), value: "Oranienbaum" },
    { label: __("Orbitron", "smart-heading"), value: "Orbitron" },
    { label: __("Oregano", "smart-heading"), value: "Oregano" },
    { label: __("Orienta", "smart-heading"), value: "Orienta" },
    { label: __("Original Surfer", "smart-heading"), value: "Original Surfer" },
    { label: __("Oswald", "smart-heading"), value: "Oswald" },
    { label: __("Over the Rainbow", "smart-heading"), value: "Over the Rainbow" },
    { label: __("Overlock", "smart-heading"), value: "Overlock" },
    { label: __("Overlock SC", "smart-heading"), value: "Overlock SC" },
    { label: __("Overpass", "smart-heading"), value: "Overpass" },
    { label: __("Overpass Mono", "smart-heading"), value: "Overpass Mono" },
    { label: __("Ovo", "smart-heading"), value: "Ovo" },
    { label: __("Oxygen", "smart-heading"), value: "Oxygen" },
    { label: __("Oxygen Mono", "smart-heading"), value: "Oxygen Mono" },
    { label: __("Pacifico", "smart-heading"), value: "Pacifico" },
    { label: __("Padauk", "smart-heading"), value: "Padauk" },
    { label: __("Palanquin", "smart-heading"), value: "Palanquin" },
    { label: __("Palanquin Dark", "smart-heading"), value: "Palanquin Dark" },
    { label: __("Pangolin", "smart-heading"), value: "Pangolin" },
    { label: __("Paprika", "smart-heading"), value: "Paprika" },
    { label: __("Parisienne", "smart-heading"), value: "Parisienne" },
    { label: __("Passero One", "smart-heading"), value: "Passero One" },
    { label: __("Passion One", "smart-heading"), value: "Passion One" },
    { label: __("Pathway Gothic One", "smart-heading"), value: "Pathway Gothic One" },
    { label: __("Patrick Hand", "smart-heading"), value: "Patrick Hand" },
    { label: __("Patrick Hand SC", "smart-heading"), value: "Patrick Hand SC" },
    { label: __("Pattaya", "smart-heading"), value: "Pattaya" },
    { label: __("Patua One", "smart-heading"), value: "Patua One" },
    { label: __("Pavanam", "smart-heading"), value: "Pavanam" },
    { label: __("Paytone One", "smart-heading"), value: "Paytone One" },
    { label: __("Pecita", "smart-heading"), value: "Pecita" },
    { label: __("Peddana", "smart-heading"), value: "Peddana" },
    { label: __("Peralta", "smart-heading"), value: "Peralta" },
    { label: __("Permanent Marker", "smart-heading"), value: "Permanent Marker" },
    { label: __("Petit Formal Script", "smart-heading"), value: "Petit Formal Script" },
    { label: __("Petrona", "smart-heading"), value: "Petrona" },
    { label: __("Phetsarath", "smart-heading"), value: "Phetsarath" },
    { label: __("Philosopher", "smart-heading"), value: "Philosopher" },
    { label: __("Piedra", "smart-heading"), value: "Piedra" },
    { label: __("Pinyon Script", "smart-heading"), value: "Pinyon Script" },
    { label: __("Pirata One", "smart-heading"), value: "Pirata One" },
    { label: __("Plaster", "smart-heading"), value: "Plaster" },
    { label: __("Play", "smart-heading"), value: "Play" },
    { label: __("Playball", "smart-heading"), value: "Playball" },
    { label: __("Playfair Display", "smart-heading"), value: "Playfair Display" },
    { label: __("Playfair Display SC", "smart-heading"), value: "Playfair Display SC" },
    { label: __("Podkova", "smart-heading"), value: "Podkova" },
    { label: __("podkovavfbeta", "smart-heading"), value: "podkovavfbeta" },
    { label: __("Poetsen One", "smart-heading"), value: "Poetsen One" },
    { label: __("Poiret One", "smart-heading"), value: "Poiret One" },
    { label: __("Poller One", "smart-heading"), value: "Poller One" },
    { label: __("Poly", "smart-heading"), value: "Poly" },
    { label: __("Pompiere", "smart-heading"), value: "Pompiere" },
    { label: __("Ponnala", "smart-heading"), value: "Ponnala" },
    { label: __("Pontano Sans", "smart-heading"), value: "Pontano Sans" },
    { label: __("Poor Story", "smart-heading"), value: "Poor Story" },
    { label: __("Poppins", "smart-heading"), value: "Poppins" },
    { label: __("Port Lligat Sans", "smart-heading"), value: "Port Lligat Sans" },
    { label: __("Port Lligat Slab", "smart-heading"), value: "Port Lligat Slab" },
    { label: __("Porter Sans Block", "smart-heading"), value: "Porter Sans Block" },
    { label: __("Post No Bills Colombo", "smart-heading"), value: "Post No Bills Colombo" },
    { label: __("Post No Bills Jaffna", "smart-heading"), value: "Post No Bills Jaffna" },
    { label: __("Pragati Narrow", "smart-heading"), value: "Pragati Narrow" },
    { label: __("Preahvihear", "smart-heading"), value: "Preahvihear" },
    { label: __("Press Start 2P", "smart-heading"), value: "Press Start 2P" },
    { label: __("Pridi", "smart-heading"), value: "Pridi" },
    { label: __("Princess Sofia", "smart-heading"), value: "Princess Sofia" },
    { label: __("Prociono", "smart-heading"), value: "Prociono" },
    { label: __("Prompt", "smart-heading"), value: "Prompt" },
    { label: __("Prosto One", "smart-heading"), value: "Prosto One" },
    { label: __("Proza Libre", "smart-heading"), value: "Proza Libre" },
    { label: __("PT Mono", "smart-heading"), value: "PT Mono" },
    { label: __("PT Sans", "smart-heading"), value: "PT Sans" },
    { label: __("PT Sans Caption", "smart-heading"), value: "PT Sans Caption" },
    { label: __("PT Sans Narrow", "smart-heading"), value: "PT Sans Narrow" },
    { label: __("PT Serif", "smart-heading"), value: "PT Serif" },
    { label: __("PT Serif Caption", "smart-heading"), value: "PT Serif Caption" },
    { label: __("Puritan", "smart-heading"), value: "Puritan" },
    { label: __("Purple Purse", "smart-heading"), value: "Purple Purse" },
    { label: __("Pushster", "smart-heading"), value: "Pushster" },
    { label: "Quando", value: "Quando" },
    { label: "Quantico", value: "Quantico" },
    { label: "Quattrocento", value: "Quattrocento" },
    { label: "Quattrocento Sans", value: "Quattrocento Sans" },
    { label: "Questrial", value: "Questrial" },
    { label: "Quicksand", value: "Quicksand" },
    { label: "Quintessential", value: "Quintessential" },
    { label: "Qwigley", value: "Qwigley" },
    { label: "Racing Sans One", value: "Racing Sans One" },
    { label: "Radley", value: "Radley" },
    { label: "Rajdhani", value: "Rajdhani" },
    { label: "Rakkas", value: "Rakkas" },
    { label: "Raleway", value: "Raleway" },
    { label: "Raleway Dots", value: "Raleway Dots" },
    { label: "Ramabhadra", value: "Ramabhadra" },
    { label: "Ramaraja", value: "Ramaraja" },
    { label: "Rambla", value: "Rambla" },
    { label: "Rammetto One", value: "Rammetto One" },
    { label: "Ranchers", value: "Ranchers" },
    { label: "Rancho", value: "Rancho" },
    { label: "Ranga", value: "Ranga" },
    { label: "Rasa", value: "Rasa" },
    { label: "Rationale", value: "Rationale" },
    { label: "Ravi Prakash", value: "Ravi Prakash" },
    { label: "Red Hat Display", value: "Red Hat Display" },
    { label: "Red Hat Text", value: "Red Hat Text" },
    { label: "Redacted", value: "Redacted" },
    { label: "Redacted Script", value: "Redacted Script" },
    { label: "Redressed", value: "Redressed" },
    { label: "Reem Kufi", value: "Reem Kufi" },
    { label: "Reenie Beanie", value: "Reenie Beanie" },
    { label: "Revalia", value: "Revalia" },
    { label: "Rhodium Libre", value: "Rhodium Libre" },
    { label: "Ribeye", value: "Ribeye" },
    { label: "Ribeye Marrow", value: "Ribeye Marrow" },
    { label: "Righteous", value: "Righteous" },
    { label: "Risque", value: "Risque" },
    { label: "Roboto", value: "Roboto" },
    { label: "Roboto Condensed", value: "Roboto Condensed" },
    { label: "Roboto Mono", value: "Roboto Mono" },
    { label: "Roboto Slab", value: "Roboto Slab" },
    { label: "Rochester", value: "Rochester" },
    { label: "Rock Salt", value: "Rock Salt" },
    { label: "Rokkitt", value: "Rokkitt" },
    { label: "Romanesco", value: "Romanesco" },
    { label: "Ropa Sans", value: "Ropa Sans" },
    { label: "Rosario", value: "Rosario" },
    { label: "Rosarivo", value: "Rosarivo" },
    { label: "Rouge Script", value: "Rouge Script" },
    { label: "roundedmplus1c", value: "roundedmplus1c" },
    { label: "Rozha One", value: "Rozha One" },
    { label: "Rubik", value: "Rubik" },
    { label: "Rubik Mono One", value: "Rubik Mono One" },
    { label: "Rubik One", value: "Rubik One" },
    { label: "Ruda", value: "Ruda" },
    { label: "Rufina", value: "Rufina" },
    { label: "Ruge Boogie", value: "Ruge Boogie" },
    { label: "Ruluko", value: "Ruluko" },
    { label: "Rum Raisin", value: "Rum Raisin" },
    { label: "Ruslan Display", value: "Ruslan Display" },
    { label: "Russo One", value: "Russo One" },
    { label: "Ruthie", value: "Ruthie" },
    { label: "Rye", value: "Rye" },
    { label: __("Sacramento", "smart-heading"), value: "Sacramento" },
    { label: __("Sahitya", "smart-heading"), value: "Sahitya" },
    { label: __("Sail", "smart-heading"), value: "Sail" },
    { label: __("Saira", "smart-heading"), value: "Saira" },
    { label: __("Saira Condensed", "smart-heading"), value: "Saira Condensed" },
    { label: __("Saira Extra Condensed", "smart-heading"), value: "Saira Extra Condensed" },
    { label: __("Saira Semi Condensed", "smart-heading"), value: "Saira Semi Condensed" },
    { label: __("Saira Stencil One", "smart-heading"), value: "Saira Stencil One" },
    { label: __("Salsa", "smart-heading"), value: "Salsa" },
    { label: __("Sanchez", "smart-heading"), value: "Sanchez" },
    { label: __("Sancreek", "smart-heading"), value: "Sancreek" },
    { label: __("Sansation", "smart-heading"), value: "Sansation" },
    { label: __("Sansita", "smart-heading"), value: "Sansita" },
    { label: __("Sansita One", "smart-heading"), value: "Sansita One" },
    { label: __("Sarabun", "smart-heading"), value: "Sarabun" },
    { label: __("Sarala", "smart-heading"), value: "Sarala" },
    { label: __("Sarina", "smart-heading"), value: "Sarina" },
    { label: __("Sarpanch", "smart-heading"), value: "Sarpanch" },
    { label: __("Satisfy", "smart-heading"), value: "Satisfy" },
    { label: __("sawarabigothic", "smart-heading"), value: "sawarabigothic" },
    { label: __("sawarabimincho", "smart-heading"), value: "sawarabimincho" },
    { label: __("Scada", "smart-heading"), value: "Scada" },
    { label: __("Scheherazade", "smart-heading"), value: "Scheherazade" },
    { label: __("Schoolbell", "smart-heading"), value: "Schoolbell" },
    { label: __("Scope One", "smart-heading"), value: "Scope One" },
    { label: __("Seaweed Script", "smart-heading"), value: "Seaweed Script" },
    { label: __("Secular One", "smart-heading"), value: "Secular One" },
    { label: __("Sedan", "smart-heading"), value: "Sedan" },
    { label: __("Sedan SC", "smart-heading"), value: "Sedan SC" },
    { label: __("Sedgwick Ave", "smart-heading"), value: "Sedgwick Ave" },
    { label: __("Sedgwick Ave Display", "smart-heading"), value: "Sedgwick Ave Display" },
    { label: __("seoulhangang", "smart-heading"), value: "seoulhangang" },
    { label: __("seoulhangangcondensed", "smart-heading"), value: "seoulhangangcondensed" },
    { label: __("seoulnamsan", "smart-heading"), value: "seoulnamsan" },
    { label: __("seoulnamsancondensed", "smart-heading"), value: "seoulnamsancondensed" },
    { label: __("seoulnamsanvertical", "smart-heading"), value: "seoulnamsanvertical" },
    { label: __("Sevillana", "smart-heading"), value: "Sevillana" },
    { label: __("Seymour One", "smart-heading"), value: "Seymour One" },
    { label: __("Shadows Into Light", "smart-heading"), value: "Shadows Into Light" },
    { label: __("Shadows Into Light Two", "smart-heading"), value: "Shadows Into Light Two" },
    { label: __("Shanti", "smart-heading"), value: "Shanti" },
    { label: __("Share", "smart-heading"), value: "Share" },
    { label: __("Share Tech", "smart-heading"), value: "Share Tech" },
    { label: __("Share Tech Mono", "smart-heading"), value: "Share Tech Mono" },
    { label: __("Shojumaru", "smart-heading"), value: "Shojumaru" },
    { label: __("Short Stack", "smart-heading"), value: "Short Stack" },
    { label: __("Shrikhand", "smart-heading"), value: "Shrikhand" },
    { label: __("Siamreap", "smart-heading"), value: "Siamreap" },
    { label: __("Siemreap", "smart-heading"), value: "Siemreap" },
    { label: __("Sigmar One", "smart-heading"), value: "Sigmar One" },
    { label: __("Signika", "smart-heading"), value: "Signika" },
    { label: __("Signika Negative", "smart-heading"), value: "Signika Negative" },
    { label: __("Simonetta", "smart-heading"), value: "Simonetta" },
    { label: __("Single Day", "smart-heading"), value: "Single Day" },
    { label: __("Sintony", "smart-heading"), value: "Sintony" },
    { label: __("Sirin Stencil", "smart-heading"), value: "Sirin Stencil" },
    { label: __("Sitara", "smart-heading"), value: "Sitara" },
    { label: __("Six Caps", "smart-heading"), value: "Six Caps" },
    { label: __("Skranji", "smart-heading"), value: "Skranji" },
    { label: __("Slabo 13px", "smart-heading"), value: "Slabo 13px" },
    { label: __("Slabo 27px", "smart-heading"), value: "Slabo 27px" },
    { label: __("Slackey", "smart-heading"), value: "Slackey" },
    { label: __("Smokum", "smart-heading"), value: "Smokum" },
    { label: __("Smythe", "smart-heading"), value: "Smythe" },
    { label: __("Sniglet", "smart-heading"), value: "Sniglet" },
    { label: __("Snippet", "smart-heading"), value: "Snippet" },
    { label: __("Snowburst One", "smart-heading"), value: "Snowburst One" },
    { label: __("Sofadi One", "smart-heading"), value: "Sofadi One" },
    { label: __("Sofia", "smart-heading"), value: "Sofia" },
    { label: __("Solway", "smart-heading"), value: "Solway" },
    { label: __("Song Myung", "smart-heading"), value: "Song Myung" },
    { label: __("Sonsie One", "smart-heading"), value: "Sonsie One" },
    { label: __("Sorts Mill Goudy", "smart-heading"), value: "Sorts Mill Goudy" },
    { label: __("souliyo", "smart-heading"), value: "souliyo" },
    { label: __("Source Code Pro", "smart-heading"), value: "Source Code Pro" },
    { label: __("Source Sans Pro", "smart-heading"), value: "Source Sans Pro" },
    { label: __("Source Serif Pro", "smart-heading"), value: "Source Serif Pro" },
    { label: __("Space Mono", "smart-heading"), value: "Space Mono" },
    { label: __("Special Elite", "smart-heading"), value: "Special Elite" },
    { label: __("Spectral", "smart-heading"), value: "Spectral" },
    { label: __("Spicy Rice", "smart-heading"), value: "Spicy Rice" },
    { label: __("Spinnaker", "smart-heading"), value: "Spinnaker" },
    { label: __("Spirax", "smart-heading"), value: "Spirax" },
    { label: __("Squada One", "smart-heading"), value: "Squada One" },
    { label: __("Sree Krushnadevaraya", "smart-heading"), value: "Sree Krushnadevaraya" },
    { label: __("Sriracha", "smart-heading"), value: "Sriracha" },
    { label: __("Srisakdi", "smart-heading"), value: "Srisakdi" },
    { label: __("Staatliches", "smart-heading"), value: "Staatliches" },
    { label: __("Stalemate", "smart-heading"), value: "Stalemate" },
    { label: __("Stalin One", "smart-heading"), value: "Stalin One" },
    { label: __("Stalinist One", "smart-heading"), value: "Stalinist One" },
    { label: __("Stardos Stencil", "smart-heading"), value: "Stardos Stencil" },
    { label: __("Stint Ultra Condensed", "smart-heading"), value: "Stint Ultra Condensed" },
    { label: __("Stint Ultra Expanded", "smart-heading"), value: "Stint Ultra Expanded" },
    { label: __("Stoke", "smart-heading"), value: "Stoke" },
    { label: __("Strait", "smart-heading"), value: "Strait" },
    { label: __("Strong", "smart-heading"), value: "Strong" },
    { label: __("Stylish", "smart-heading"), value: "Stylish" },
    { label: __("Sue Ellen Francisco", "smart-heading"), value: "Sue Ellen Francisco" },
    { label: __("Suez One", "smart-heading"), value: "Suez One" },
    { label: __("Sumana", "smart-heading"), value: "Sumana" },
    { label: __("Sunflower", "smart-heading"), value: "Sunflower" },
    { label: __("Sunshiney", "smart-heading"), value: "Sunshiney" },
    { label: __("Supermercado One", "smart-heading"), value: "Supermercado One" },
    { label: __("Sura", "smart-heading"), value: "Sura" },
    { label: __("Suranna", "smart-heading"), value: "Suranna" },
    { label: __("Suravaram", "smart-heading"), value: "Suravaram" },
    { label: __("Suwannaphum", "smart-heading"), value: "Suwannaphum" },
    { label: __("Swanky and Moo Moo", "smart-heading"), value: "Swanky and Moo Moo" },
    { label: __("Syncopate", "smart-heading"), value: "Syncopate" },
    { label: __("Tajawal", "smart-heading"), value: "Tajawal" },
    { label: __("Tangerine", "smart-heading"), value: "Tangerine" },
    { label: __("Taprom", "smart-heading"), value: "Taprom" },
    { label: __("Tauri", "smart-heading"), value: "Tauri" },
    { label: __("Taviraj", "smart-heading"), value: "Taviraj" },
    { label: __("Teko", "smart-heading"), value: "Teko" },
    { label: __("Telex", "smart-heading"), value: "Telex" },
    { label: __("Tenali Ramakrishna", "smart-heading"), value: "Tenali Ramakrishna" },
    { label: __("Tenor Sans", "smart-heading"), value: "Tenor Sans" },
    { label: __("Terminal Dosis", "smart-heading"), value: "Terminal Dosis" },
    { label: __("Terminal Dosis Light", "smart-heading"), value: "Terminal Dosis Light" },
    { label: __("Text Me One", "smart-heading"), value: "Text Me One" },
    { label: __("Thabit", "smart-heading"), value: "Thabit" },
    { label: __("tharlon", "smart-heading"), value: "tharlon" },
    { label: __("Thasadith", "smart-heading"), value: "Thasadith" },
    { label: __("The Girl Next Door", "smart-heading"), value: "The Girl Next Door" },
    { label: __("Tienne", "smart-heading"), value: "Tienne" },
    { label: __("Tillana", "smart-heading"), value: "Tillana" },
    { label: __("Timmana", "smart-heading"), value: "Timmana" },
    { label: __("Tinos", "smart-heading"), value: "Tinos" },
    { label: __("Titan One", "smart-heading"), value: "Titan One" },
    { label: __("Titillium Web", "smart-heading"), value: "Titillium Web" },
    { label: __("Trade Winds", "smart-heading"), value: "Trade Winds" },
    { label: __("Trirong", "smart-heading"), value: "Trirong" },
    { label: __("Trocchi", "smart-heading"), value: "Trocchi" },
    { label: __("Trochut", "smart-heading"), value: "Trochut" },
    { label: __("Trykker", "smart-heading"), value: "Trykker" },
    { label: __("Tuffy", "smart-heading"), value: "Tuffy" },
    { label: __("Tulpen One", "smart-heading"), value: "Tulpen One" },
    { label: __("Ubuntu", "smart-heading"), value: "Ubuntu" },
    { label: __("Ubuntu Condensed", "smart-heading"), value: "Ubuntu Condensed" },
    { label: __("Ubuntu Mono", "smart-heading"), value: "Ubuntu Mono" },
    { label: __("Ultra", "smart-heading"), value: "Ultra" },
    { label: __("Uncial Antiqua", "smart-heading"), value: "Uncial Antiqua" },
    { label: __("Underdog", "smart-heading"), value: "Underdog" },
    { label: __("Unica One", "smart-heading"), value: "Unica One" },
    { label: __("UnifrakturCook", "smart-heading"), value: "UnifrakturCook" },
    { label: __("UnifrakturMaguntia", "smart-heading"), value: "UnifrakturMaguntia" },
    { label: __("Unkempt", "smart-heading"), value: "Unkempt" },
    { label: __("Unlock", "smart-heading"), value: "Unlock" },
    { label: __("Unna", "smart-heading"), value: "Unna" },
    { label: __("Vampiro One", "smart-heading"), value: "Vampiro One" },
    { label: __("Varela", "smart-heading"), value: "Varela" },
    { label: __("Varela Round", "smart-heading"), value: "Varela Round" },
    { label: __("Varta", "smart-heading"), value: "Varta" },
    { label: __("Vast Shadow", "smart-heading"), value: "Vast Shadow" },
    { label: __("Vesper Libre", "smart-heading"), value: "Vesper Libre" },
    { label: __("Vibur", "smart-heading"), value: "Vibur" },
    { label: __("Vidaloka", "smart-heading"), value: "Vidaloka" },
    { label: __("Viga", "smart-heading"), value: "Viga" },
    { label: __("Voces", "smart-heading"), value: "Voces" },
    { label: __("Volkhov", "smart-heading"), value: "Volkhov" },
    { label: __("Vollkorn", "smart-heading"), value: "Vollkorn" },
    { label: __("Vollkorn SC", "smart-heading"), value: "Vollkorn SC" },
    { label: __("Voltaire", "smart-heading"), value: "Voltaire" },
    { label: __("VT323", "smart-heading"), value: "VT323" },
    { label: __("Waiting for the Sunrise", "smart-heading"), value: "Waiting for the Sunrise" },
    { label: __("Wallpoet", "smart-heading"), value: "Wallpoet" },
    { label: __("Walter Turncoat", "smart-heading"), value: "Walter Turncoat" },
    { label: __("Warnes", "smart-heading"), value: "Warnes" },
    { label: __("Wellfleet", "smart-heading"), value: "Wellfleet" },
    { label: __("Wendy One", "smart-heading"), value: "Wendy One" },
    { label: __("Wire One", "smart-heading"), value: "Wire One" },
    { label: __("Work Sans", "smart-heading"), value: "Work Sans" },
    { label: __("Yaldevi Colombo", "smart-heading"), value: "Yaldevi Colombo" },
    { label: __("Yanone Kaffeesatz", "smart-heading"), value: "Yanone Kaffeesatz" },
    { label: __("Yantramanav", "smart-heading"), value: "Yantramanav" },
    { label: __("Yatra One", "smart-heading"), value: "Yatra One" },
    { label: __("Yellowtail", "smart-heading"), value: "Yellowtail" },
    { label: __("Yeon Sung", "smart-heading"), value: "Yeon Sung" },
    { label: __("Yeseva One", "smart-heading"), value: "Yeseva One" },
    { label: __("Yesteryear", "smart-heading"), value: "Yesteryear" },
    { label: __("Yinmar", "smart-heading"), value: "Yinmar" },
    { label: __("Yrsa", "smart-heading"), value: "Yrsa" },
    { label: __("ZCOOL KuaiLe", "smart-heading"), value: "ZCOOL KuaiLe" },
    { label: __("ZCOOL QingKe HuangYou", "smart-heading"), value: "ZCOOL QingKe HuangYou" },
    { label: __("ZCOOL XiaoWei", "smart-heading"), value: "ZCOOL XiaoWei" },
    { label: __("Zeyada", "smart-heading"), value: "Zeyada" },
    { label: __("Zhi Mang Xing", "smart-heading"), value: "Zhi Mang Xing" },
    { label: __("Zilla Slab Highlight", "smart-heading"), value: "Zilla Slab Highlight" },
];
